# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 637e4ebbfc8e95c8e9845e6a52ed8c77c69532152886a04a725703344b6f881facbfbc55570e97a57b25b0e195f69922977d13c9027680c86f3ba77bb9a0ff53

test:
  secret_key_base: e4e87315cda82b66e279012d10aa6de7d8bca6291f7029ff132be62fa7b47d115b50e1d663019c6e062108a845feab52320f45bb90ebbe707e8ec946b706f8e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
